### ISSUE TITLE
Add support for python tests

### ISSUE THREAD

**Issue by mikeferguson** [mikeferguson/code_coverage#1]

**Comment by Ishadijcks** [comment]
Is there any progress being made on this issue?
I quite like the tool and python support would make it perfect.

**Comment by mikeferguson** [comment]
I haven't really dug into this yet as most of the codebases I'm working with right now are exclusively C++.

**Comment by Ishadijcks** [comment]
Do you have any idea/pointers on how to add it? Maybe I can take a look at it.

**Comment by mikeferguson** [comment]
Implemented in https://github.com/mikeferguson/code_coverage/pull/18 - planning to merge in a day or so (in case anyone else notices issues with it)
