### ISSUE TITLE
Support for catkin tools?

### ISSUE THREAD

**Issue by romainreignier** [mikeferguson/code_coverage#2]
Nice package!
I have already tried to do code coverage on ROS packages and I had to write some scripts to call the lcov stuff by hand and with hardcoded paths so this package is welcomed!

But do you know how to invoke it with [catkin tools](http://catkin-tools.readthedocs.io/en/latest/)?

Thanks

**Comment by mikeferguson** [comment]
So, in theory, this should work:
```
catkin config --cmake-args -DENABLE_COVERAGE_TESTING=ON
catkin build PACKAGE_NAME --no-deps
catkin build PACKAGE_NAME -v -no-deps --catkin-make-args PACKAGE_NAME_coverage
```
And that does appear to run things, but for some reason the extraction fails part way through... although the files it is working on look identical to what is generated through catkin_make.

I'm not sure what is going on -- will have to take a closer look later.

**Comment by mikeferguson** [comment]
Appears to be some sort of escaping issue? The following patch appears to work with both catkin_build and catkin_make: https://github.com/mikeferguson/code_coverage/commit/f3fc68dc7767121686b3199ccc6266883c816708

If you have a chance to try those commands with the catkin_build_fix branch, do let me know how it goes.

**Comment by romainreignier** [comment]
Thanks!

With the fix, the command you gave me works fine but not with `master` version.

Actually, I was missing the `--catkin-make-args` part in the catkin tools command.

**Comment by mikeferguson** [comment]
Great. I’m going to add my command set to the readme and then I’ll get that merged into master and released

**Comment by romainreignier** [comment]
Do you plan to release it for Melodic too?

**Comment by mikeferguson** [comment]
It was released into Melodic before Kinetic -- but the sync hasn't happened yet.

**Comment by romainreignier** [comment]
Oh, great!
