### ISSUE TITLE
Some gtests get no coverage

### ISSUE THREAD

**Issue by samlcharreyron** [mikeferguson/code_coverage#21]
Hi,

I stumbled across your package which could really come in handy. I'm having an issue where I can see some my c++ google tests are not getting picked up by the coverage report. It's strange because they are written the exact same way as the other tests which are themselves correctly indexed by gcov. 

![image](https://user-images.githubusercontent.com/451016/80492656-a408da80-8964-11ea-985a-71297f5ade6a.png)

I'm building the coverage report with the following flags

```
catkin build mag_manip --no-deps --cmake-args -DENABLE_COVERAGE_TESTING=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-fno-inline -fno-inline-small-functions -fno-default-inline"

catkin build mag_manip -v --no-deps --catkin-make-args mag_manip_coverage_report
```

Do you have any suggestions how to debug this? Thanks in advance.

**Comment by mikeferguson** [comment]
I've not seen this before -- is this an open source package that I could locally reproduce?

The console output should show exactly what files are being processed when generating the report - if those files aren't in the list, then maybe the tests aren't running as part of the coverage target?

**Comment by samlcharreyron** [comment]
Unfortunately it's not an open source package that I can share. What is strange is that all the tests are compiled using the same commands in CMakeLists.txt. 

I can see that the gcno files are created but for some, the gcda files are not generated. I'm a bit confused because all the tests are defined in the same way. Also running the make target 
make <package>_coverage_report_cpp seems to generate the missing gcda files.

I guess this might be hard to troubleshoot.

**Comment by mikeferguson** [comment]
> I guess this might be hard to troubleshoot.

Yeah, without a reproducible sample for me to look at, you're pretty much on your own, since I've never seen this before.

**Comment by samlcharreyron** [comment]
Thanks anyway, I totally understand. I was just wondering if you might have an idea what I could look into. Feel free to close the issue.

**Comment by mikeferguson** [comment]
> Thanks anyway, I totally understand. I was just wondering if you might have an idea what I could look into. Feel free to close the issue.

If you do happen to figure out what the cause is, please do report back!
