### ISSUE TITLE
Uses python-coverage (Python 2) on Noetic

### ISSUE THREAD

**Issue by StefanFabian** [mikeferguson/code_coverage#26]
Thank you for this ROS wrapper, I have used it for quite some time now on kinetic and melodic.
Unfortunately, it doesn't work on my Travis CI for noetic anymore for the following reason:
While the package correctly depends on `python3-coverage` for `$ROS_PYTHON_VERSION==3`, the command used is still `python-coverage` regardless of the ROS python version.
This obviously causes the process to fail on noetic as python-coverage is not installed (but python3-coverage is).

https://github.com/mikeferguson/code_coverage/blob/8aad31ce71c9c05facdf3885a2048aa6c4d79e4a/cmake/Modules/CodeCoverage.cmake#L147-L151

https://github.com/mikeferguson/code_coverage/blob/8aad31ce71c9c05facdf3885a2048aa6c4d79e4a/cmake/Modules/CodeCoverage.cmake#L172-L182

**Comment by StefanFabian** [comment]
Could you please make a new noetic release so my noetic CI pipeline will work again? :)

**Comment by mikeferguson** [comment]
> Could you please make a new noetic release so my noetic CI pipeline will work again? :)

Release was cut two weeks ago - I'm not sure when it will get sync'd to public - https://github.com/ros/rosdistro/pull/27191
